//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class chi_tiet_san_pham
    {
        public int id_san_pham { get; set; }
        [DisplayName("Màn hình")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public string man_hinh { get; set; }
        [DisplayName("Độ phân giải")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public string do_phan_giai { get; set; }
        [DisplayName("Tần số quét")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public int tan_so_quet { get; set; }
        [DisplayName("Cam sau")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public int cam_sau { get; set; }
        [DisplayName("Cam trước")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public int cam_truoc { get; set; }
        [DisplayName("CPU")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public string cpu { get; set; }
        [DisplayName("RAM")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public int ram { get; set; }
        [DisplayName("Dung lượng lưu trữ")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public int rom { get; set; }
        [DisplayName("Sim")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public int sim { get; set; }
        [DisplayName("Chân sạc")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public string chan_sac { get; set; }
        [DisplayName("Dung lượng pin")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public int dung_luong_pin { get; set; }
    
        public virtual san_pham san_pham { get; set; }
    }
}
