//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class nha_cung_cap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nha_cung_cap()
        {
            this.san_pham = new HashSet<san_pham>();
        }
    
        public int id { get; set; }
        [DisplayName("Tên nhà cung cấp")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public string ten_nha_cung_cap { get; set; }
        [DisplayName("Tên người đại diện")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public string ten_nguoi_dai_dien { get; set; }
        [DisplayName("Số điện thoại")]
        public string so_dien_thoai { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Fax")]
        public string fax { get; set; }
        [DisplayName("Địa chỉ")]
        public string dia_chi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<san_pham> san_pham { get; set; }
    }
}
