//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class san_pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public san_pham()
        {
            this.chi_tiet_hoa_don = new HashSet<chi_tiet_hoa_don>();
        }
    
        public int id { get; set; }
        [DisplayName("Ảnh sản phẩm")]
        public byte[] anh_san_pham { get; set; }
        [DisplayName("Tên sản phẩm")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public string ten_san_pham { get; set; }
        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public int so_luong { get; set; }
        [DisplayName("Đơn giá")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public long don_gia { get; set; }
        [DisplayName("Giảm giá")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        [Range(0,100,ErrorMessage = "Không hợp lệ")]
        public Nullable<int> giam_gia { get; set; }
        public int id_hang_san_xuat { get; set; }
        public int id_nha_cung_cap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_hoa_don> chi_tiet_hoa_don { get; set; }
        public virtual chi_tiet_san_pham chi_tiet_san_pham { get; set; }
        public virtual hang_san_xuat hang_san_xuat { get; set; }
        public virtual nha_cung_cap nha_cung_cap { get; set; }
    }
}
