//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tai_khoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tai_khoan()
        {
            this.hoa_don = new HashSet<hoa_don>();
        }
    
        public int id { get; set; }
        [DisplayName("Họ tên")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public string ho_ten { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public string email { get; set; }
        [DisplayName("Ảnh đại diện")]
        public byte[] anh_dai_dien { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        [StringLength(50, MinimumLength = 4, ErrorMessage = "Mật khẩu tối thiểu 4 ký tự")]
        public string mat_khau { get; set; }
        public int id_vai_tro { get; set; }
        [DisplayName("Trạng thái")]
        public bool trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoa_don> hoa_don { get; set; }
        public virtual vai_tro vai_tro { get; set; }
    }
}
